## Numpy Library

This library provide support for arrays and matrices, along with a collection of mathematical functions to operate on these data structures.

In [ ]:
# %pip install numpy


   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ----------- ---------------------------- 3.7/12.6 MB 24.2 MB/s eta 0:00:01
   --------------------------------- ------ 10.7/12.6 MB 29.2 MB/s eta 0:00:01
   ---------------------------------------- 12.6/12.6 MB 26.4 MB/s eta 0:00:00


In [ ]:
import numpy as np;

## creating a array with numpy 

arr1 = np.array([1,2,4,5,6]);
print(arr1, type(arr1)) 
print(arr1.shape) # shape no of row and column 



[1 2 4 5 6] <class 'numpy.ndarray'>
(5,)


In [ ]:
arr2 = np.array([1,2,4,3,5,6]); 
arr2.reshape(1,6); # one row 5 column 

array([[1, 2, 4, 3, 5, 6]])

In [12]:
arr3 = np.array([[1, 3, 4,3,4], [23, 56, 7, 3, 7]], 
                # dtype=object
              )
print(arr3, arr3.shape) # both array should be of same size 

[[ 1  3  4  3  4]
 [23 56  7  3  7]] (2, 5)


In [16]:
## array with in build fncs 
arr4 = np.arange(0,10,2) # starting point , ending , difference 
print(arr4)
arr4.reshape(5,1) # now it has 5 rows and 1 column 


[0 2 4 6 8]


array([[0],
       [2],
       [4],
       [6],
       [8]])

In [19]:
# np.ones((3,4)); # r row and 4 columns 

## identity matrix 

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
## Attributes of NP

arr = np.array([[1,2,3,4], [5,6,7,8]])

print('Array: \n', arr);
print('Shape: \n', arr.shape);
print('Number of dimenison: \n', arr.ndim); 
print('Size : \n', arr.size);
print('Data type : \n', arr.dtype);
print('Item size : \n', arr.itemsize);

Array: 
 [[1 2 3 4]
 [5 6 7 8]]
Shape: 
 (2, 4)
Number of dimenison: 
 2
Size : 
 8
Data type : 
 int64
Item size : 
 8


In [30]:
## Numpy Vectorized Operations

arr5 = np.array([12,13,14,15]); 
arr6 = np.array([1,23,3,4]); 


lst = [12,34,55,5]; 
lst1 = [122,343,545,55];
# print(lst + lst1) 
#  # this is add both lists but numpy performs maths functions 


## All operations are performed elements wise means index with same index 
print('additions : ', arr5 + arr6); 

print('subtractions', arr5 - arr6);
print('multiple', arr6 * arr5);




additions :  [13 36 17 19]
subtractions [ 11 -10  11  11]
multiple [ 12 299  42  60]


In [34]:
## Universal fncs = apply to entire array 

arr7 = np.array([25,4,49,225,16]); 

print(np.sqrt(arr7)); 

print(np.log(arr7),'\n')

print(np.sin(arr7), '\n')

print(np.exp(arr7) , '\n')


[ 5.  2.  7. 15.  4.]
[3.21887582 1.38629436 3.8918203  5.4161004  2.77258872] 

[-0.13235175 -0.7568025  -0.95375265 -0.93009488 -0.28790332] 

[7.20048993e+10 5.45981500e+01 1.90734657e+21 5.20305514e+97
 8.88611052e+06] 



In [56]:
## array slicing and operations 

arr8 = np.array([[1,2,4,5], [3,8,6,5], [12,32,3,4]])

print('Array \n', arr8); 

## accessing elements 

# print('arr of 2nd row elem 2 \n',arr8[1][2] )

# print('two elem from different row \n',arr8[1:,2:]); 

# print(arr8[0:2,2:]);

print(arr8[1:,1:3])


Array 
 [[ 1  2  4  5]
 [ 3  8  6  5]
 [12 32  3  4]]
[[ 8  6]
 [32  3]]


In [59]:
## Modify array element 
arr[0,0] = 100; 
arr[1:] = 100
print(arr
)

[[100   2   3   4]
 [100 100 100 100]]


In [60]:
## statisticcal Concepts = normalization
# to have a mean of 0 and standard deviation of 1

data = np.array([1,2,3,4,5]); 

mean = np.mean(data); 
std_dev = np.std(data); 

normalization = (data - mean) / std_dev

print('Normalixed data', normalization)

Normalixed data [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [65]:
data1 = np.array([1,2,3,4,5,6,7,8])

mean = np.mean(data1); 
# print(mean)

median = np.median(data1)
print(median)

std_dev = np.std(data1);
print('std',std_dev);

variance = np.var(data1)
print(variance)

4.5
std 2.29128784747792
5.25


In [66]:
## logical operations 

data3 = np.array([2,34,5,33,2,5]); 
d5 = data3[data3>=5]
print(d5)

[34  5 33  5]
