# Module: NumPy Assignments
## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [1]:
import numpy as np


In [ ]:
# Create a NumPy array of shape (5, 5) filled with random integers

# shape5_5 = np.random.randint(1,21, size = (5,5));
shape5 = np.random.randint(1,21,size = (5,5));
# print("Original Array : ", shape5); 


shape5[:, 2] = 1 # sabke 2nd index ki value 1 se replace kardo 
print("Modified array:")
print(shape5)


Modified array:
[[19 17  1  7  7]
 [ 4  4  1 10 18]
 [ 8  3  1 18 19]
 [17  1  1 13 11]
 [ 7 17  1 20 18]]


In [9]:
arr2 = np.random.randint(1,16,size=(4,4))
# print(arr2)

np.fill_diagonal(arr2,0); 
print(arr2)


[[ 0  1  9  3]
 [ 9  0 10 10]
 [11  8  0 13]
 [11 12  4  0]]


In [12]:
arr3 = np.random.randint(1,36,size=(6,6));
print("Original array:")
print(arr3)

# Extract the sub-array
sub_arr = arr3[2:5,1:4]; 
# 3nd index se 5th index tak ; aur :2nd se 4th column
print('modify');
print(sub_arr)

Original array:
[[26 11 33 34 30 29]
 [14 18 34 12 25 35]
 [ 5 21 35 33 30 30]
 [33 19 12 17 28 21]
 [ 4 18 22 12  8 13]
 [14  6 13  5  1 29]]
modify
[[21 35 33]
 [19 12 17]
 [18 22 12]]


In [ ]:
shape5 = np.random.randint(1,21,size = (5,5));
print(shape5)

border_elem = np.concatenate((shape5[0,:], shape5[-1,:]));
## 0 index se last tak ka aur last se row
print('border')
print(border_elem); 

[[ 8 12  8  7 18]
 [ 7 10 14 14  8]
 [18 10  7 16  6]
 [ 1 12  4 17  7]
 [13 18 17 19 12]]
border
[ 8 12  8  7 18 13 18 17 19 12]


In [16]:
array1 = np.random.randint(1, 11, size=(3, 4))
array2 = np.random.randint(1, 11, size=(3, 4))
print("Array 1:")
# print(array1)
print("Array 2:")
# print(array2)

print(f'add {array1 + array2}')
print(f'sub {array1 - array2}')
print(f'mul {array1 * array2}')

Array 1:
Array 2:
add [[13 13 12 10]
 [10  3 13  8]
 [19 13  4  6]]
sub [[-1 -3 -6  0]
 [ 8 -1  5  4]
 [ 1  7  0 -4]]
mul [[42 40 27 25]
 [ 9  2 36 12]
 [90 30  4  5]]


In [ ]:
arr2 = np.random.randint(1,16,size=(4,4));

row_sum = np.sum(arr2,axis=1); # axis 1 -- row target
col_sum = np.sum(arr2,axis=0); # axis 0 -- column target 

print("Row-wise sum:");
print(row_sum);
print("Column-wise sum:");
print(col_sum);


Row-wise sum:
[41 21 46 27]
Column-wise sum:
[17 39 39 40]


In [18]:
array = np.random.randint(1, 21, size=(5, 5))

mean = np.mean(array);
med = np.median(array);
std_dev = np.std(array);
variance = np.var(array);


print("Mean:", mean)
print("Median:", med)
print("Standard Deviation:", std_dev)
print("Variance:", variance)

Mean: 9.88
Median: 9.0
Standard Deviation: 6.748748032042683
Variance: 45.54559999999999


In [ ]:
array = np.arange(1, 10).reshape((3, 3))

## normalization - the array formula -> 
# array - mean / divide std_Dev

mean = np.mean(array);
std_dev = np.std(array);
normalized = (array - mean) / std_dev;

print(normalized); 
# it return  every single normalized version of array elem 



[[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]


In [ ]:
## Broadcasting 

arr = np.random.randint(1,11,size=(3,3)); 
row_Arr = np.random.randint(1,11,size = (3,));
print("Original array:")
print(arr)
print("1D array:")
print(row_Arr)

# we have two arrays 

res = arr + row_Arr;
print("Resulting array:");
print(res);


Original array:
[[ 8  5  5]
 [ 4  2  9]
 [10  7  3]]
1D array:
[10  9  4]
Resulting array:
[[18 14  9]
 [14 11 13]
 [20 16  7]]


In [ ]:
# Create a NumPy array of shape (4, 4) filled with random integers
array = np.random.randint(1, 11, size=(4, 4))
column_array = np.random.randint(1, 11, size=(4,))
print("Original array:")
print(array)
print("1D array:")
print(column_array)

result = array - column_array[:,np.newaxis];
print("Resulting array:")
print(result);


Original array:
[[ 1  1  6  7]
 [ 8 10  5  3]
 [ 4  3  7  8]
 [ 7  4  8  8]]
1D array:
[3 5 1 7]
Resulting array:
[[-2 -2  3  4]
 [ 3  5  0 -2]
 [ 3  2  6  7]
 [ 0 -3  1  1]]


In [ ]:
matrix = np.random.randint(1, 11, size=(3, 3));
print("Original matrix:");
print(matrix);

deter = np.linalg.det(matrix);
print('Deter :', deter);

inverse = np.linalg.inv(matrix);
print('Inverse', inverse);

eigenvalues = np.linalg.eigvals(matrix);
print('eigenvalues', eigenvalues);


Original matrix:
[[7 5 6]
 [1 4 3]
 [3 8 5]]
Deter : -32.000000000000014
Inverse [[ 0.125   -0.71875  0.28125]
 [-0.125   -0.53125  0.46875]
 [ 0.125    1.28125 -0.71875]]
eigenvalues [13.05457738  3.62215916 -0.67673655]


In [30]:
# Create two NumPy arrays of shape (2, 3) and (3, 2)
array1 = np.random.randint(1, 11, size=(2, 3))
array2 = np.random.randint(1, 11, size=(3, 2))
print("Array 1:")
print(array1)
print("Array 2:")
print(array2)

res = np.dot(array1,array2);
print('mulitple');
print(res); 

Array 1:
[[ 2  6 10]
 [ 2  8  5]]
Array 2:
[[ 9  6]
 [ 2  9]
 [10 10]]
mulitple
[[130 166]
 [ 84 134]]


In [ ]:
arr8 = np.arange(1,10).reshape((3,3));
print(arr8);

reshaped_arr = arr8.reshape((1,9));
print(reshaped_arr);

new_res = reshaped_arr.reshape((9,1));
print(new_res);


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3 4 5 6 7 8 9]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [35]:
array = np.random.randint(1,21,size = (5,5)); 

flattened  = array.flatten()
print(flattened)

[ 1  8 15 11 17  6  2  3  5  9 11 13  8  5  3 14 14 11 17 18  6  3  3  6
 10]


In [ ]:
# Create a NumPy array of shape (5, 5) filled with random integers
array = np.random.randint(1, 21, size=(5, 5))
print("Original array:")
print(array)


# Use fancy indexing to extract the elements at the corners of the array

corners = array[[0,0,-1,-1], [0,-1,0,-1]];
print(corners);



Original array:
[[17 16  4  8  4]
 [ 4  6 10  4 13]
 [ 9 11 17  4 10]
 [14 18  5 15  2]
 [ 6 15  8 15 19]]
[17  4  6 19]


In [ ]:
array = np.random.randint(1, 21, size=(4, 4))
print("Original array:")
print(array); 

array[array > 10] = 10;
print('Modified');
print(array);



Original array:
[[ 3 10 20  9]
 [14  7  2  6]
 [ 3  7  9 14]
 [ 7 10 10 15]]
Modified
[[ 3 10 10  9]
 [10  7  2  6]
 [ 3  7  9 10]
 [ 7 10 10 10]]


In [41]:
# Create a structured array with fields 'name', 'age', and 'weight'

data_type = [('name','U10'), ('age','i4'),('weight', 'f4')];

data = np.array([('Alice', 25,55.5), ('bob',30,85.4), ('charlie',20,65.3)],dtype= data_type);

print(data);

sorted_data = np.sort(data,order = 'age');
print('sorted array by age :'); 
print(sorted_data)

[('Alice', 25, 55.5) ('bob', 30, 85.4) ('charlie', 20, 65.3)]
sorted array by age :
[('charlie', 20, 65.3) ('Alice', 25, 55.5) ('bob', 30, 85.4)]


In [42]:
# Create a structured array with fields 'x' and 'y'

data_type = [('x','i4'),('y','i4')];
data = np.array([(1,2), (3,4), (5,6)] , dtype= data_type); 
print("Original array:")
print(data);

distances = np.sqrt((data['x'][:,np.newaxis] - data['x'])** 2 + (data['y'][:,np.newaxis] - data['y']** 2));

print("Euclidean distances:")
print(distances)

Original array:
[(1, 2) (3, 4) (5, 6)]
Euclidean distances:
[[       nan        nan        nan]
 [2.                nan        nan]
 [4.24264069        nan        nan]]


C:\Users\pawar\AppData\Local\Temp\ipykernel_12832\4145709456.py:8: RuntimeWarning: invalid value encountered in sqrt
  distances = np.sqrt((data['x'][:,np.newaxis] - data['x'])** 2 + (data['y'][:,np.newaxis] - data['y']** 2));


In [43]:
import numpy.ma as ma

In [46]:
arr = np.random.randint(1,21, size=(4,4));
masked_Array = ma.masked_greater(arr,10);
print("Original array:")
print(arr)
print("Masked array:")
print(masked_Array)

#  Compute the sum of the unmasked elements
sum_unmasked = masked_Array.sum()
print("Sum of unmasked elements:", sum_unmasked)

Original array:
[[ 2  2 17 19]
 [17 20 17  7]
 [ 1  3 15  6]
 [17 18  9  6]]
Masked array:
[[2 2 -- --]
 [-- -- -- 7]
 [1 3 -- 6]
 [-- -- 9 6]]
Sum of unmasked elements: 36


In [ ]:
arr = np.random.randint(1,21,size=(3,3));
masked_arr = ma.masked_array(arr,mask= np.eye(3,dtype=bool));
print("Original array:")
print(array)
print("Masked array:")
print(masked_arr);


mean_unmasked = masked_arr.mean();
masked_arrrr = masked_arr.filled(mean_unmasked);
print("Modified masked array:");
print(masked_arrrr);


Original array:
[[ 3 10 10  9]
 [10  7  2  6]
 [ 3  7  9 10]
 [ 7 10 10 10]]
Masked array:
[[-- 1 6]
 [4 -- 17]
 [5 14 --]]
Modified masked array:
[[ 7  1  6]
 [ 4  7 17]
 [ 5 14  7]]
